kind: pipeline
type: docker
name: build dev

steps:
  - name: build for staging
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      registry: hub.fsisp.de
      repo: hub.fsisp.de/library/iassure-wx
      username:
        from_secret: reg_username
      password:
        from_secret: reg_password
      tags:
        - dev
        - '${DRONE_COMMIT:0:8}'
    when:
      branch:
        - dev
        - develop
      event:
        - push

  - name: build for production
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      registry: hub.fsisp.de
      repo: hub.fsisp.de/library/iassure-wx
      username:
        from_secret: reg_username
      password:
        from_secret: reg_password
      tags:
        - latest
        - '${DRONE_TAG}'
        - '${DRONE_COMMIT:0:8}'
    when:
      event:
        - tag
